algoritmo "ex004"
var
    numero1, numero2, soma: inteiro
inicio

    // Solicita ao usuário que digite o primeiro valor
   escreva("Digite um valor: ")
   leia(numero1)

   // Solicita ao usuário que digite o segundo valor
   escreva("Digite outro valor: ")
   leia(numero2)

   // Calcula o somatório entre os dois números
   soma <- numero1 + numero2

   // Exibe o resultado
   escreva("A soma entre ", numero1, " e ", numero2, " é igual a ", soma, ".")
fimalgoritmo

